function [q_vals] = pollution_level(dt, num_steps)
% Inputs:
% > dt is the length of the subintervals making up the full time interval
% > num_steps is the number of times the iterated map is applied

q_vals = zeros(1, num_steps + 1);

for k = 1:num_steps
    q_vals(1, k+1) = ((1- (dt/2))*q_vals(1, k)) + (10*dt) + (5*dt*sin(2*(k-1)*dt));
    % did k-1 for the last term because q_vals(1,1) is actually q^(0)
end
    
% Output:
% > q_vals is a 1 x (num_steps + 1) row vector, i.e. 1 row and num_steps+1
%   columns. The first component of q_vals is the initial condition (= 0) 
%   and the values of q^(k) generated by the iterated map in eq. (6) are
%   the other components (in chronological order)

end